api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

api_route:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

rest_api:
    type:     rest
    prefix:   /
    resource: "@ApiBundle/Resources/config/api-routing.yml"