<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskListRepository extends EntityRepository
{
}
